Static versions of particle objects
balt-dev/robot-is-chill pull request #144
Opened 2024-04-27 04:39 UTC by FofoFromBaba

i tried very hard to make sure all of these colors are accurate to the in-game ones.
please let me know if there are formatting errors
also fixes the background_rain tile, and sets all of them to tiling -2. hopefully that doesn't cause any issues

2024-04-27 11:33 UTC, balt-dev requested changes
tiling _-2_ will need special handling in the bot
i'm gonna wait to pull this until that's added
bc of how this works, i'm gonna allow you to do code changes in the same pr, BUT
you gotta test it on a selfhost first to make sure shit don't break

2024-04-27 14:22 UTC, FofoFromBaba commented
i've actually selfhosted ric a while back, and while using it an object with this tiling type didn't seem to cause any issues
i also can't see anything in the code to suggest it would, but i might've missed something?

2024-04-27 15:51 UTC, FofoFromBaba commented
i'll just revert them to tiling -1 for now, doesn't seem like that big of a deal but it _would_ be nice to indicate how none of these don't really correspond to the normal tiling types

2024-05-25 13:21 UTC, balt-dev approved these changes

2024-05-25 13:21 UTC, merged